version: "3.8"
services:
  syslogserver:
    image: pbertera/syslogserver
    container_name: syslogserver
    environment:
      - SYSLOG_USERNAME=admin
      - SYSLOG_PASSWORD=123456
    ports:
      - 5514:514/udp
      - 8081:80/tcp
    restart: unless-stopped
    networks:
      - net

networks:
  net:
